apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- values.yaml
- repository.yaml
- helmrelease.yaml
- dashboards/gpu-dashboard.yaml
- prometheus-route.yaml
- grafana-route.yaml
