apiVersion: v1
kind: ConfigMap
metadata:
  name: kps-values
  namespace: monitoring
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        externalUrl: http://0.0.0.0:9090/prometheus
        routePrefix: /prometheus
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi

    alertmanager:
      alertmanagerSpec:
        externalUrl: http://0.0.0.0:9093/alertmanager
        routePrefix: /alertmanager

    grafana:
      enabled: true
      grafana.ini:
        server:
          #root_url: http://0.0.0.0/grafana
          root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
          serve_from_sub_path: true
      persistence:
        enabled: true
        type: sts
        accessModes: ["ReadWriteOnce"]
        size: 20Gi
        finalizers:
        - kubernetes.io/pvc-protection
