apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# infra
- ../../infrastructure/namespaces/base
- ../../infrastructure/namespaces/gpu
- ../../infrastructure/networking

# platform
- ../../platform/monitoring

# GPU stack
- ../../rtx/cluster-addons

# app
- ../../apps/mlflow
- ../../apps/llm-serving
