apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: mlflow
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: mlflow
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        args: ["server", "/data"]
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: minio-root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: minio-root-password
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /data
          name: data

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: mlflow
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: mlflow
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mc
        image: minio/mc
        env:
        - name: MINIO_USER
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: minio-root-user
        - name: MINIO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: minio-root-password
        command:
        - sh
        - -c
        - |
          set -e

          echo "Waiting for MinIO..."
          for i in $(seq 1 30); do
            mc alias set minio http://minio:9000 $MINIO_USER $MINIO_PASSWORD && break
            sleep 2
          done

          echo "Creating bucket..."
          mc ls minio/mlflow || mc mb -p minio/mlflow

          echo "Done"

