apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
  namespace: mlflow
type: Opaque
stringData:
  # Postgres
  postgres-user: mlflow
  postgres-password: mlflow
  postgres-db: mlflow

  # MinIO
  minio-root-user: minio
  minio-root-password: minio123

