apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ngf
  namespace: nginx-gateway
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: nginx-gateway-fabric
    namespace: flux-system
  install:
    createNamespace: true
  values:
    nginx:
      service:
        type: NodePort
      nodePorts:
      - port: 30080
        listenerPort: 80
