apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# infra
- ../../infrastructure/namespaces/base
- ../../infrastructure/networking

# platform
- ../../platform/monitoring

# app
- ../../apps/mlflow
